model:
    verbose: 0
    cores: 7
    seed: 1993
    rand_sampled: 1000
    train_mat_bin_path: data/mat_bin_train_test.npz
    train_mat_count_path: data/mat_count_train_test.npz
    eval_mat_path: data/mat_bin_validate_test.npz 
    slim_W: slim_W_test.npz
    shutdown: 1
    top_n_performances:
        - 4
        - 10
        - 20
        - 50
