model:
    verbose: 0
    cores: 8
    seed: 1993
    rand_sampled: 1000
    train_mat_path: data/mat_bin_train_test.npz
    eval_mat_path: data/mat_bin_validate_test.npz
    shutdown: 0
    top_n_performances:
        - 4
        - 10
        - 20
        - 50
