model:
    verbose: 1
    cores: 7
    seed: None
    rand_sampled: 1000
    train_mat_bin_path: data/mat_bin_train_test.npz
    train_mat_count_path: data/mat_count_train_test.npz
    eval_mat_path: data/mat_bin_validate_test.npz
    batch_size: 2000
    max_epochs: 100
    max_epochs_without_improvement: 6
    n_random_samples: 10
    model_path: Mult_VAE.torchmodel
    shutdown: 0
    top_n_performances:
        - 4
        - 10
        - 20
        - 50
